# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

readme = ''

setup(
    long_description=readme,
    name='fastapi-users',
    version='0.1.0',
    description='Ready-to-use and customizable users management for FastAPI.',
    python_requires='==3.*,>=3.8.0',
    author='JeffreyThijs',
    author_email='jeffrey.thijs@hotmail.com',
    packages=[
        'fastapi_users', 'fastapi_users.authentication', 'fastapi_users.db',
        'fastapi_users.router'
    ],
    package_dir={"": "."},
    package_data={},
    install_requires=[
        'databases[sqlite]<0.5,>=0.3.0', 'email-validator<1.2,>=1.1.0',
        'fastapi<0.62.0,>=0.54.0', 'makefun<1.10,>=1.9.2',
        'motor<3.0.0,>=2.2.0', 'passlib[bcrypt]==1.7.4', 'pyjwt==1.7.1',
        'python-multipart==0.0.5', 'sqlalchemy<1.4,>=1.3.13',
        'tortoise-orm<0.17.0,>=0.15.18'
    ],
    extras_require={
        "dev": [
            "asgi-lifespan", "asynctest", "black==20.*,>=20.8.0.b1",
            "bumpversion", "codecov", "flake8", "flake8-docstrings", "flit",
            "httpx", "httpx-oauth", "isort", "markdown-include", "mkdocs",
            "mkdocs-material", "mypy", "pygments", "pymdown-extensions",
            "pytest", "pytest-asyncio", "pytest-cov", "pytest-mock", "requests",
            "uvicorn"
        ]
    },
)
